#define PORT_MOTORS 12
#define STARBOARD_MOTORS 13

#define LED_RING_PORT 38
#define LED_RING_STARBOARD 39

#define LED_STRIP_PORT 34
#define LED_STRIP_STARBOARD 35

#define IR_FRONT_PORT A0
#define IR_FRONT_STARBOARD A1
#define IR_BACK_PORT A2
#define IR_BACK_STARBOARD A3

#define PHYSICAL_ESTOP A4


